"""allow pending analysis versions

Revision ID: b6b9e9b1b47d
Revises: b99b7c7282ae
Create Date: 2026-09-18 14:19:12.295544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b9e9b1b47d'
down_revision: Union[str, Sequence[str], None] = 'b99b7c7282ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'analyzer_version',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('analyses', 'model_version',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'model_version',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('analyses', 'analyzer_version',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
