"""add movement illustration path

Revision ID: b99b7c7282ae
Revises: fc60f55e064b
Create Date: 2026-09-17 15:30:57.567738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99b7c7282ae'
down_revision: Union[str, Sequence[str], None] = 'fc60f55e064b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('illustration_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movements', 'illustration_path')
    # ### end Alembic commands ###
