"""create core application schema

Revision ID: fc60f55e064b
Revises: 
Create Date: 2026-09-16 19:32:06.585928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc60f55e064b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('family_key', sa.Text(), nullable=False),
    sa.Column('upload_analysis_supported', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('live_coach_supported', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('stripe_price_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (code = 'free' AND stripe_price_id IS NULL)\n            OR (code = 'pro' AND stripe_price_id IS NOT NULL)\n            ", name='ck_subscription_plans_price_mapping'),
    sa.CheckConstraint("code IN ('free', 'pro')", name='ck_subscription_plans_code'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('stripe_price_id')
    )
    op.create_table('plan_entitlements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('feature_key', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('allowance_units', sa.Integer(), nullable=False),
    sa.Column('reset_policy', sa.Text(), server_default=sa.text("'calendar_month_utc'"), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("feature_key IN ('video_analysis', 'training_plan_generation', 'ai_coach_reply')", name='ck_plan_entitlements_feature_key'),
    sa.CheckConstraint("reset_policy = 'calendar_month_utc'", name='ck_plan_entitlements_reset_policy'),
    sa.CheckConstraint('allowance_units >= 0', name='ck_plan_entitlements_allowance_units'),
    sa.CheckConstraint('revision > 0', name='ck_plan_entitlements_revision'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'feature_key', 'effective_from', name='uq_plan_entitlements_plan_feature_effective')
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('app_role', sa.Text(), server_default=sa.text("'athlete'"), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coaching_context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('initial_assessment', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('athlete_state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('safety_ack_version', sa.Text(), nullable=True),
    sa.Column('safety_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("app_role IN ('athlete', 'admin')", name='ck_profiles_app_role'),
    sa.CheckConstraint('\n            (safety_ack_version IS NULL AND safety_acknowledged_at IS NULL)\n            OR\n            (safety_ack_version IS NOT NULL AND safety_acknowledged_at IS NOT NULL)\n            ', name='ck_profiles_safety_ack_pair'),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_usage',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entitlement_id', sa.UUID(), nullable=False),
    sa.Column('feature_key', sa.Text(), nullable=False),
    sa.Column('operation_key', sa.Text(), nullable=False),
    sa.Column('request_fingerprint', sa.Text(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'reserved'"), nullable=False),
    sa.Column('reservation_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (status = 'reserved' AND settled_at IS NULL)\n            OR (status IN ('consumed', 'released') AND settled_at IS NOT NULL)\n            ", name='ck_feature_usage_settlement'),
    sa.CheckConstraint("feature_key IN ('video_analysis', 'training_plan_generation', 'ai_coach_reply')", name='ck_feature_usage_feature_key'),
    sa.CheckConstraint("status IN ('reserved', 'consumed', 'released')", name='ck_feature_usage_status'),
    sa.CheckConstraint('units > 0', name='ck_feature_usage_units'),
    sa.CheckConstraint('window_end > window_start', name='ck_feature_usage_window_bounds'),
    sa.ForeignKeyConstraint(['entitlement_id'], ['plan_entitlements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feature_key', 'operation_key', name='uq_feature_usage_user_feature_operation')
    )
    op.create_index('ix_feature_usage_quota_lookup', 'feature_usage', ['user_id', 'feature_key', 'window_start', 'status'], unique=False)
    op.create_table('movement_documentation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edit_revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (status = 'draft' AND published_by IS NULL AND published_at IS NULL)\n            OR (status = 'published' AND published_at IS NOT NULL)\n            OR (status = 'archived')\n            ", name='ck_movement_documentation_publication_state'),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_movement_documentation_status'),
    sa.CheckConstraint('edit_revision > 0', name='ck_movement_documentation_edit_revision'),
    sa.CheckConstraint('version > 0', name='ck_movement_documentation_version'),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_id', 'version', name='uq_movement_documentation_movement_version')
    )
    op.create_index('uq_movement_documentation_one_draft', 'movement_documentation', ['movement_id'], unique=True, postgresql_where=sa.text("status = 'draft'"))
    op.create_index('uq_movement_documentation_one_published', 'movement_documentation', ['movement_id'], unique=True, postgresql_where=sa.text("status = 'published'"))
    op.create_table('training_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('plan_document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('provider_status', sa.Text(), nullable=True),
    sa.Column('effective_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('stripe_subscription_id', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('checkout_operation_key', sa.Text(), nullable=True),
    sa.Column('checkout_session_id', sa.Text(), nullable=True),
    sa.Column('checkout_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_id', sa.Text(), nullable=True),
    sa.Column('last_event_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider_status IS NULL OR provider_status IN ('active','past_due','incomplete','incomplete_expired','unpaid','canceled','paused','trialing')", name='ck_user_subscriptions_provider_status'),
    sa.CheckConstraint('\n            (current_period_start IS NULL AND current_period_end IS NULL)\n            OR (current_period_start IS NOT NULL AND current_period_end IS NOT NULL AND current_period_end > current_period_start)\n            ', name='ck_user_subscriptions_period_bounds'),
    sa.CheckConstraint('\n            (effective_start IS NULL AND effective_end IS NULL)\n            OR (effective_start IS NOT NULL AND effective_end IS NOT NULL AND effective_end > effective_start)\n            ', name='ck_user_subscriptions_effective_bounds'),
    sa.CheckConstraint('sync_revision > 0', name='ck_user_subscriptions_sync_revision'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_operation_key'),
    sa.UniqueConstraint('checkout_session_id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('safety_documentation_id', sa.UUID(), nullable=False),
    sa.Column('safety_ack_version', sa.Text(), nullable=False),
    sa.Column('safety_acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_usage_id', sa.UUID(), nullable=True),
    sa.Column('owner_kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'reserved'"), nullable=False),
    sa.Column('stage', sa.Text(), server_default=sa.text("'reserved'"), nullable=False),
    sa.Column('video_path', sa.Text(), nullable=True),
    sa.Column('guest_token_hash', sa.Text(), nullable=True),
    sa.Column('guest_rate_key', sa.Text(), nullable=True),
    sa.Column('reservation_operation_key', sa.Text(), nullable=False),
    sa.Column('request_fingerprint', sa.Text(), nullable=False),
    sa.Column('reservation_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('video_delete_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('claim_token', sa.Text(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('progress_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_feedback_status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('analyzer_version', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n                owner_kind = 'guest'\n                AND user_id IS NULL\n                AND guest_token_hash IS NOT NULL\n                AND guest_rate_key IS NOT NULL\n                AND access_expires_at IS NOT NULL\n                AND purge_after IS NOT NULL\n                AND feature_usage_id IS NULL\n            )\n            OR\n            (\n                owner_kind = 'authenticated'\n                AND user_id IS NOT NULL\n                AND guest_token_hash IS NULL\n                AND guest_rate_key IS NULL\n                AND access_expires_at IS NULL\n                AND purge_after IS NULL\n            )\n            ", name='ck_analyses_ownership_shape'),
    sa.CheckConstraint("ai_feedback_status IN ('pending', 'running', 'completed', 'failed', 'skipped')", name='ck_analyses_ai_feedback_status'),
    sa.CheckConstraint("owner_kind IN ('guest', 'authenticated')", name='ck_analyses_owner_kind'),
    sa.CheckConstraint("status <> 'running' OR (claim_token IS NOT NULL AND lease_expires_at IS NOT NULL)", name='ck_analyses_running_claim'),
    sa.CheckConstraint("status IN ('reserved', 'queued', 'running', 'completed', 'failed', 'expired')", name='ck_analyses_status'),
    sa.CheckConstraint('attempts >= 0', name='ck_analyses_attempts'),
    sa.ForeignKeyConstraint(['feature_usage_id'], ['feature_usage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['safety_documentation_id'], ['movement_documentation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_usage_id'),
    sa.UniqueConstraint('reservation_operation_key')
    )
    op.create_index('ix_analyses_guest_abuse_window', 'analyses', ['guest_rate_key', 'created_at'], unique=False)
    op.create_index('ix_analyses_worker_queue', 'analyses', ['status', 'created_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'completed'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_messages_role'),
    sa.CheckConstraint("status IN ('streaming', 'completed', 'failed', 'interrupted')", name='ck_messages_status'),
    sa.CheckConstraint('position >= 0', name='ck_messages_position'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'position', name='uq_messages_conversation_position')
    )
    op.create_table('workout_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('training_plan_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'self_reported', 'uploaded_analysis', 'live_coach')", name='ck_workout_sessions_source'),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name='ck_workout_sessions_time_order'),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('feature_usage_id', sa.UUID(), nullable=True),
    sa.Column('feature', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('operation_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'reserved'"), nullable=False),
    sa.Column('reserved_cost', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('temporary_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('reserved', 'running', 'completed', 'failed', 'interrupted')", name='ck_ai_runs_status'),
    sa.CheckConstraint('\n            (temporary_result IS NULL AND result_expires_at IS NULL)\n            OR (temporary_result IS NOT NULL AND result_expires_at IS NOT NULL)\n            ', name='ck_ai_runs_temporary_result_expiry'),
    sa.CheckConstraint('actual_cost IS NULL OR actual_cost >= 0', name='ck_ai_runs_actual_cost'),
    sa.CheckConstraint('reserved_cost >= 0', name='ck_ai_runs_reserved_cost'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feature_usage_id'], ['feature_usage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_key')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('hold_seconds', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('analysis_segment_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'self_reported', 'uploaded_analysis', 'live_coach')", name='ck_workout_sets_source'),
    sa.CheckConstraint('\n            (analysis_id IS NULL AND analysis_segment_key IS NULL)\n            OR (analysis_id IS NOT NULL AND analysis_segment_key IS NOT NULL)\n            ', name='ck_workout_sets_analysis_segment_pair'),
    sa.CheckConstraint('\n            (reps IS NOT NULL AND reps >= 0 AND hold_seconds IS NULL)\n            OR (reps IS NULL AND hold_seconds IS NOT NULL AND hold_seconds > 0)\n            ', name='ck_workout_sets_primary_value'),
    sa.CheckConstraint('position >= 0', name='ck_workout_sets_position'),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'position', name='uq_workout_sets_session_position')
    )
    op.create_index('uq_workout_sets_analysis_segment', 'workout_sets', ['analysis_id', 'analysis_segment_key'], unique=True, postgresql_where=sa.text('analysis_id IS NOT NULL'))
    
    application_tables = [
        "profiles",
        "movements",
        "movement_documentation",
        "analyses",
        "workout_sessions",
        "workout_sets",
        "training_plans",
        "conversations",
        "messages",
        "ai_runs",
        "subscription_plans",
        "plan_entitlements",
        "user_subscriptions",
        "feature_usage",
    ]

    for table in application_tables:
        op.execute(
            sa.text(
                f'ALTER TABLE public."{table}" ENABLE ROW LEVEL SECURITY'
            )
        )
        op.execute(
            sa.text(
                f'REVOKE ALL PRIVILEGES ON TABLE public."{table}" '
                "FROM anon, authenticated"
            )
        )   

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_workout_sets_analysis_segment', table_name='workout_sets', postgresql_where=sa.text('analysis_id IS NOT NULL'))
    op.drop_table('workout_sets')
    op.drop_table('ai_runs')
    op.drop_table('workout_sessions')
    op.drop_table('messages')
    op.drop_index('ix_analyses_worker_queue', table_name='analyses')
    op.drop_index('ix_analyses_guest_abuse_window', table_name='analyses')
    op.drop_table('analyses')
    op.drop_table('user_subscriptions')
    op.drop_table('training_plans')
    op.drop_index('uq_movement_documentation_one_published', table_name='movement_documentation', postgresql_where=sa.text("status = 'published'"))
    op.drop_index('uq_movement_documentation_one_draft', table_name='movement_documentation', postgresql_where=sa.text("status = 'draft'"))
    op.drop_table('movement_documentation')
    op.drop_index('ix_feature_usage_quota_lookup', table_name='feature_usage')
    op.drop_table('feature_usage')
    op.drop_table('conversations')
    op.drop_table('profiles')
    op.drop_table('plan_entitlements')
    op.drop_table('subscription_plans')
    op.drop_table('movements')
    # ### end Alembic commands ###
